#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PHYSICS_GUIDED=1
export SEMANTIC_GUARD=1
export ADAPTIVE_FUSION="${ADAPTIVE_FUSION:-1}"
export ADAPTER_EPOCHS="${ADAPTER_EPOCHS:-15}"
export EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-3}"
export LEARNING_RATE="${LEARNING_RATE:-0.0005}"
export PHYSICS_WEIGHT="${PHYSICS_WEIGHT:-1.0}"
export ANCHOR_WEIGHT="${ANCHOR_WEIGHT:-0.5}"
export RANKING_WEIGHT="${RANKING_WEIGHT:-0.5}"
export RANKING_TEMPERATURE="${RANKING_TEMPERATURE:-0.2}"
export RESIDUAL_SCALE="${RESIDUAL_SCALE:-0.2}"
export RESIDUAL_LR_MULTIPLIER="${RESIDUAL_LR_MULTIPLIER:-5.0}"

exec bash "$ROOT/scripts/run_cloud_p2_local.sh"
